baseURL = "http://example.org/"
languageCode = "en-us"
title = "handsomehome.net"
theme = "ezhil"

copyright = "© 2021 Jarle Fagerheim"

[params]
    subtitle = "Jarle Fagerheim"
    customCSS = "custom.css"
