baseURL = "https://handsomehome.net/"
languageCode = "en-us"
title = "handsomehome.net"
theme = "ezhil"

copyright = "© 2021 Jarle Fagerheim"
defaultContentLanguage = "no"


[params]
    subtitle = "Jarle Fagerheim"
    customCSS = "custom.css"

[languages]
    [languages.no]
        [languages.no.params]
            subtitle = "Jarle Fagerheims hjørne av verdsveven"


    [languages.en]
        [languages.en.params]
            subtitle = "Jarle Fagerheim's corner of the World Wide Web"
